language: go
go:
  - 1.7.1
env:
  global:
  - GIT_NAME="Nathan Moos"
  - GIT_EMAIL="moosingin3space@gmail.com"
git:
  submodules: false
branches:
  only:
    - master
before_install:
  - openssl aes-256-cbc -K $encrypted_e4367039b9c5_key -iv $encrypted_e4367039b9c5_iv
    -in travis_key.enc -out travis_key -d
  - chmod 0600 travis_key
  - eval `ssh-agent -s`
  - ssh-add travis_key
  - git submodule update --init --recursive
before_script:
  - go get -u -v github.com/spf13/hugo
script:
  - "./deploy.sh"
